---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install prerequisites
  ansible.builtin.apt:
    pkg:
    - php{{ php_version }}
    - php{{ php_version }}-cli
    - php{{ php_version }}-curl
    - php{{ php_version }}-fpm
    - php{{ php_version }}-gd
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mysql
    - php{{ php_version }}-opcache
    - php{{ php_version }}-xml
    state: present
