---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install prerequisites
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: "Install MySQL server {{ mysql_version }}"
  ansible.builtin.apt:
    name: "mysql-server={{ mysql_version }}"
    state: present

- name: Ensure MySQL operational
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    name: ''
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create WordPress DB
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create WordPress DB user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
