---
- name: Download WordPress
  ansible.builtin.get_url:
    url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp/wordpress-{{ wp_version }}.tar.gz"

- name: Unpack WordPress
  ansible.builtin.unarchive:
    src: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    dest: /var/www/
    remote_src: yes

- name: Copy contents of folder into new path
  ansible.builtin.copy:
    remote_src: true
    src: /var/www/wordpress/
    dest: "/var/www/{{ public_domain }}"

- name: Remove old file
  ansible.builtin.file:
    path: /var/www/wordpress
    state: absent

- name: Get NGINX service file metadata
  stat:
    path: "{{ wp_html_path }}/wp-config-sample.php"
  register: wp_file_metadata

- name: Copy a "sudoers" file on the remote machine for editing
  ansible.builtin.copy:
    src: "{{ wp_html_path }}/wp-config-sample.php"
    dest: "{{ wp_html_path }}/wp-config.php"
    remote_src: yes
  when: wp_file_metadata.stat.exists

- name: Configure WordPress DB name
  ansible.builtin.replace:
    path: "{{ wp_html_path }}/wp-config.php"
    regexp: "database_name_here"
    replace: "{{ wp_db_name }}"

- name: Configure WordPress DB username
  ansible.builtin.replace:
    path: "{{ wp_html_path }}/wp-config.php"
    regexp: "username_here"
    replace: "{{ wp_db_user }}"

- name: Configure WordPress DB user password
  ansible.builtin.replace:
    path: "{{ wp_html_path }}/wp-config.php"
    regexp: "password_here"
    replace: "{{ wp_db_password }}"
